title: CG Conference Deadlines # (Maintained by @ryanzhe)
# email: zhe66@gatech.edu
description: Countdowns to top Computer Graphics (& related fields) conference deadlines
author: Ziming He

domain: "cgdeadlines.date"
baseurl: ""

# twitter_username: abhshkdz
# twitter_hashtag: machinelearning
github_username: ryanzhe
github_repo: cg-deadlines

markdown: kramdown
ga_id: UA-36274081-2
